package tp1.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import tp1.entity.Matchs;
import tp1.repository.MatchsRepository;

@RestController // This means that this class is a Controller
@RequestMapping(path="/matchs") // This means URL's start with /matchs (after Application path)
public class MatchsController {
  @Autowired // This means to get the bean called matchsRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private MatchsRepository matchsRepository;

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Matchs> getAllMatchs() {
    // This returns a JSON or XML with the users
    return matchsRepository.findAll();
  }

  @GetMapping(path="/{id}")
  public Matchs getMatchById(@PathVariable Integer id) {
    return matchsRepository.findById(id).orElse(null);
  }

  @PostMapping(path="/add") // Map ONLY POST Requests
  public Matchs addNewMatch(@RequestBody Matchs match) {
    // @RequestBody maps the HttpRequest body to a transfer or domain object
    return matchsRepository.save(match);
  }

  @PutMapping(path="/{id}")
  public Matchs updateMatch(@PathVariable Integer id, @RequestBody Matchs matchDetails) {
    Matchs match = matchsRepository.findById(id).orElse(null);
    if (match != null) {
      match.setDateHeure(matchDetails.getDateHeure());
      match.setNomEquipeAdverse(matchDetails.getNomEquipeAdverse());
      match.setLieu(matchDetails.getLieu());
      match.setAdresse(matchDetails.getAdresse());
      match.setResultat(matchDetails.getResultat());
      return matchsRepository.save(match);
    }
    return null;
  }

  @DeleteMapping(path="/{id}")
  public String deleteMatch(@PathVariable Integer id) {
    matchsRepository.deleteById(id);
    return "Match supprimé";
  }
}
