package tp1.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import tp1.entity.Participation;
import tp1.repository.ParticipationRepository;

@RestController // This means that this class is a Controller
@RequestMapping(path="/participations") // This means URL's start with /participations (after Application path)
public class ParticipationController {
  @Autowired // This means to get the bean called participationRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ParticipationRepository participationRepository;

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Participation> getAllParticipations() {
    // This returns a JSON or XML with the participations
    return participationRepository.findAll();
  }

  @GetMapping(path="/{id}")
  public Participation getParticipationById(@PathVariable Integer id) {
    return participationRepository.findById(id).orElse(null);
  }

  @GetMapping(path="/match/{matchId}")
  public Iterable<Participation> getParticipationsByMatch(@PathVariable Integer matchId) {
    return participationRepository.findByMatchId(matchId);
  }

  @GetMapping(path="/joueur/{joueurId}")
  public Iterable<Participation> getParticipationsByJoueur(@PathVariable Integer joueurId) {
    return participationRepository.findByJoueurId(joueurId);
  }

  @PostMapping(path="/add") // Map ONLY POST Requests
  public Participation addNewParticipation(@RequestBody Participation participation) {
    // @RequestBody maps the HttpRequest body to a transfer or domain object
    return participationRepository.save(participation);
  }

  @PutMapping(path="/{id}")
  public Participation updateParticipation(@PathVariable Integer id, @RequestBody Participation details) {
    Participation participation = participationRepository.findById(id).orElse(null);
    if (participation != null) {
      participation.setFeuilleMatch(details.getFeuilleMatch());
      participation.setPoste(details.getPoste());
      participation.setEstCapitaine(details.isEstCapitaine());
      participation.setEvaluation(details.getEvaluation());
      participation.setCommentaire(details.getCommentaire());
      if (details.getJoueur() != null) {
        participation.setJoueur(details.getJoueur());
      }
      if (details.getMatch() != null) {
        participation.setMatch(details.getMatch());
      }
      return participationRepository.save(participation);
    }
    return null;
  }

  @DeleteMapping(path="/{id}")
  public String deleteParticipation(@PathVariable Integer id) {
    participationRepository.deleteById(id);
    return "Participation supprimée";
  }
}
